### ISSUE TITLE
Infografía hilos Castro Rodríguez Betsabe Aricel 

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/infografia-de-hilos-AricelCastro#2]
[INFOGRAFIA HILOS CASTRO RODRIGUEZ BETSABE ARICEL.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-AricelCastro/files/15043813/INFOGRAFIA.HILOS.CASTRO.RODRIGUEZ.BETSABE.ARICEL.pdf)

**Comment by Aylin67** [comment]
18.5% FALTO APLICACIÓN

**Comment by josealfredo79** [comment]
bien hecho y revisado..
